### ISSUE TITLE
vfat_shuffler: cannot import name 'Embedded' from 'construct'

### ISSUE THREAD

**Issue by cweiske** [mk-fg/fgtk#18]
When running vfat_shuffler.py with the latest construct installed, I get an error:

> Traceback (most recent call last):
>  File "./bin/vfat_shuffler.py", line 3, in <module>
>    from construct import (
> ImportError: cannot import name 'Embedded' from 'construct' (/usr/local/lib/python3.8/dist-packages/construct/__init__.py)

The reason is that "Embedded" is [not part of construct anymore](https://construct.readthedocs.io/en/latest/transition210.html) since v2.10.

Workaround:
```
pip3 install construct==2.9.52
```

(Info taken from https://github.com/rytilahti/python-yeelightbt/issues/36)

**Comment by mk-fg** [comment]
Yeah, looks like I'm using it with construct installed for pypy3 here since god knows when, so don't really notice these changes.
Apparently new way to combine fields of different structs is to just add them together.
Should be fixed in 3cf9ecf, and this addition seem to also be supported in older construct module (2.9.x), so should work with both old and new one now.
Thanks for reporting.

**Comment by cweiske** [comment]
Thanks, works fine with construct 2.10.56 now.
